// src/templates/frontend/rsbuild-vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { invoke } from "./suji";

const name = ref("Suji");
const log = ref("Ready. 백엔드 핸들러를 호출해 보세요.");

async function call(label: string, run: () => Promise<unknown>) {
  try {
    log.value = `[${label}] ${JSON.stringify(await run())}`;
  } catch (e) {
    log.value = `[${label}] ERR: ${String(e)}`;
  }
}
</script>

<template>
  <main class="wrap">
    <h1>Suji + Vue</h1>
    <p class="hint"><code>import { invoke } from "./suji"</code></p>

    <div class="row">
      <button @click="call('ping', () => invoke('ping'))">
        invoke("ping")
      </button>
      <input v-model="name" aria-label="name" />
      <button @click="call('greet', () => invoke('greet', { name }))">
        invoke("greet", { name })
      </button>
    </div>

    <pre class="log">{{ log }}</pre>
  </main>
</template>

<style>
.wrap {
  max-width: 560px;
  margin: 0 auto;
  padding: 32px;
  font-family: system-ui, sans-serif;
}
.hint {
  color: #888;
}
.row {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
  margin-top: 24px;
}
.log {
  margin-top: 24px;
  padding: 14px;
  background: #111;
  color: #0f0;
  border-radius: 6px;
  white-space: pre-wrap;
}
</style>

// packages/suji-cli/templates/frontend/solid/src/App.tsx
import { createSignal } from "solid-js";
import { invoke } from "./suji";

export default function App() {
  const [name, setName] = createSignal("Suji");
  const [log, setLog] = createSignal("Ready. 백엔드 핸들러를 호출해 보세요.");

  const call = (label: string, run: () => Promise<unknown>) => async () => {
    try {
      setLog(`[${label}] ${JSON.stringify(await run())}`);
    } catch (e) {
      setLog(`[${label}] ERR: ${String(e)}`);
    }
  };

  return (
    <main
      style={{
        "max-width": "560px",
        margin: "0 auto",
        padding: "32px",
        "font-family": "system-ui, sans-serif",
      }}
    >
      <h1>Suji + Solid</h1>
      <p style={{ color: "#888" }}>
        <code>import {"{ invoke }"} from "./suji"</code>
      </p>

      <div
        style={{
          display: "flex",
          gap: "8px",
          "flex-wrap": "wrap",
          "margin-top": "24px",
        }}
      >
        <button onClick={call("ping", () => invoke("ping"))}>
          invoke("ping")
        </button>
        <input
          value={name()}
          onInput={(e) => setName(e.currentTarget.value)}
          aria-label="name"
        />
        <button onClick={call("greet", () => invoke("greet", { name: name() }))}>
          invoke("greet", {"{ name }"})
        </button>
      </div>

      <pre
        style={{
          "margin-top": "24px",
          padding: "14px",
          background: "#111",
          color: "#0f0",
          "border-radius": "6px",
          "white-space": "pre-wrap",
        }}
      >
        {log()}
      </pre>
    </main>
  );
}
